"""Build the Remix Icon CSS/font subset used by DtKit.

The original Remix Icon CSS and font remain checked in as the reproducible source.
Run this script after adding or removing an ``ri-*`` icon class in ``src``.
"""

from __future__ import annotations

import re
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
SOURCE_CSS = SRC / "assets" / "remixicon.css"
SOURCE_FONT = SRC / "assets" / "fonts" / "remixicon.woff2"
OUTPUT_CSS = SRC / "assets" / "remixicon-subset.css"
OUTPUT_FONT = SRC / "assets" / "fonts" / "remixicon-subset.woff2"

ICON_REFERENCE = re.compile(r"\bri-[a-z0-9]+(?:-[a-z0-9]+)*\b")
ICON_DEFINITION = re.compile(
    r"\.([a-z0-9-]+):before\s*\{\s*content:\s*\"\\([0-9a-f]+)\";\s*\}",
    re.IGNORECASE,
)
SOURCE_SUFFIXES = {".css", ".html", ".js"}


def read_icon_map() -> dict[str, int]:
    css = SOURCE_CSS.read_text(encoding="utf-8")
    return {name: int(codepoint, 16) for name, codepoint in ICON_DEFINITION.findall(css)}


def collect_used_icons(icon_map: dict[str, int]) -> list[str]:
    references: set[str] = set()
    ignored = {SOURCE_CSS.resolve(), OUTPUT_CSS.resolve()}

    for path in SRC.rglob("*"):
        if not path.is_file() or path.suffix not in SOURCE_SUFFIXES:
            continue
        if path.resolve() in ignored:
            continue
        content = path.read_text(encoding="utf-8")
        references.update(ICON_REFERENCE.findall(content))

    # Template strings can expose partial names such as ``ri-star``. Only complete
    # class names present in the upstream icon map are valid subset candidates.
    return sorted(references.intersection(icon_map), key=icon_map.__getitem__)


def build_css(icons: list[str], icon_map: dict[str, int]) -> str:
    lines = [
        "/* Generated by scripts/build-remixicon-subset.py. Do not edit manually. */",
        f"/* {len(icons)} project icon glyphs retained from the local Remix Icon asset. */",
        "@font-face {",
        "  font-family: 'remixicon';",
        "  src: url('fonts/remixicon-subset.woff2') format('woff2');",
        "  font-display: swap;",
        "}",
        "",
        '[class^="ri-"], [class*=" ri-"] {',
        "  font-family: 'remixicon' !important;",
        "  font-style: normal;",
        "  -webkit-font-smoothing: antialiased;",
        "  -moz-osx-font-smoothing: grayscale;",
        "}",
        "",
    ]
    lines.extend(
        f'.{name}:before {{ content: "\\{icon_map[name]:x}"; }}' for name in icons
    )
    return "\n".join(lines) + "\n"


def build_font(codepoints: set[int]) -> None:
    options = subset.Options()
    options.flavor = "woff2"
    options.with_zopfli = False
    font = TTFont(SOURCE_FONT)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    font.save(OUTPUT_FONT)


def main() -> None:
    icon_map = read_icon_map()
    icons = collect_used_icons(icon_map)
    if not icons:
        raise SystemExit("No Remix Icon references were found in src")

    OUTPUT_CSS.write_text(build_css(icons, icon_map), encoding="utf-8", newline="\n")
    build_font({icon_map[name] for name in icons})

    print(
        f"Built Remix Icon subset: {len(icons)} glyphs, "
        f"{OUTPUT_CSS.stat().st_size} byte CSS, {OUTPUT_FONT.stat().st_size} byte font."
    )


if __name__ == "__main__":
    main()
